- global_config:
    autoCreateTestUsers:
      createForGroupNamesRegEx: "(testgroup)-.*"
      prefix: "testuser-"
      name: "TU %{group.name}"
      path: /home/users/myproj-test-users
      impersonationAllowedFor: [dummy]

- group_config:

    - testgroup-tags:

       - name: Test group for tag management
         isMemberOf: 
         members: 
         path: t

    - dummygroup-dam:

        - name: Dummy group for DAM management
          isMemberOf:
          members:
          path: d

- ace_config:

    - testgroup-tags:

       - path: /content/cq:tags
         permission: allow
         actions: read
         privileges:

    - dummygroup-dam:

        - path: /content/dam
          permission: allow
          actions: read
          privileges:

- user_config:
    - dummy:
        - isMemberOf: dummygroup-dam
          password: "password"
